name = "Yames SP"
author = "hexagonelle"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5057952a679741070d04b0240ea7b2e63cc5a82f57ba7a64e9addb697555ec6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = "1.20"
datapack-folder = "config\\paxi\\datapacks"
no-internal-hashes = true
