name = "Yames SP"
author = "hexagonelle"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6278617c01d261c0e4c2dac0ec3594d0080bc8beb9288d64e982228de66c7f7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = "1.20"
datapack-folder = "config\\paxi\\datapacks"
no-internal-hashes = true
